# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["mandy@cpan.org"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = ""
language = "javascript"
manifest_version = 3
name = "scte35-ads"
service_id = ""

[local_server]

  [local_server.kv_stores]

    [[local_server.kv_stores.videos]]
      key = "sampleAd.m3u8"
      file = "./videos/sampleAd.m3u8"
    [[local_server.kv_stores.videos]]
      key = "sampleAd.mp4"
      file = "./videos/sampleAd.mp4"
    [[local_server.kv_stores.videos]]
      key = "sampleAd0.ts"
      file = "./videos/sampleAd0.ts"
    [[local_server.kv_stores.videos]]
      key = "sampleAd1.ts"
      file = "./videos/sampleAd1.ts"
    [[local_server.kv_stores.videos]]
      key = "sampleAd2.ts"
      file = "./videos/sampleAd2.ts"

[scripts]
  build = "npm run build"
  post_init = "npm install"
